
dict = {

    "5:30 AM": "Wake up for Fajr",
    "6:00 AM": "Its 6AM, wake up now",
    "6:30 AM": "You better wake up now",
    "7:00 AM": "Lets go to the park",
    "7:30 AM": "Time for some Duolingo!",
    "8:00 AM": "Remember your goals",
    "8:30 AM": "....",
    "9:00 AM": "Make sure your in home",
    "9:30 AM": "Gaming time",
    "10:00 AM": "Duolingo time",
    "10:30 AM": "Duolingo time",
    "11:00 AM": "Open up the Pharmacy",
    "11:30 AM": "Web app reading",
    "12:00 PM": "Focus, Focus",
    "12:30 PM": "Never Forget who you are",
    "1:00 PM": "Pray Zohar Salah",
    "1:30 PM": "Are you home?",
    "2:00 PM": "Hacking time!",
    "2:30 PM": "Duolingo",
    "3:00 PM": "Exercise",
    "3:30 PM": "LOl",
    "4:00 PM": "Time for Asr, drop all work now",
    "4:30 PM": "Reach home now",
    "5:00 PM": "Time for tuition",
    "5:30 PM": "Study hard :)",
    "6:00 PM": "Stop looking at your phone",
    "6:30 PM": "Focus, Focus",
    "7:00 PM": "Head home now",
    "7:30 PM": "Any pending work?",
    "8:00 PM": "Maybe head over to the Pharmacy",
    "8:30 PM": "Read Web app book",
    "9:00 PM": "Dinner bOi",
    "9:30 PM": "Gaming Time",
    "10:00 PM": "Close your console now",
    "10:30 PM": "Consider sleeping",
    "11:00 PM": "Clean up all your feed",
    "11:30 PM": 'Are you still awake?',

}
